name: bidrag-stonad
ingress: https://bidrag-stonad.intern.nav.no
dbname: bidrag-stonad-prod
kafka:
  pool: nav-prod
kafka-topic-vedtak: bidrag.vedtak
spec:
  replicas:
    min: 2
  gcp:
    sqlInstances:
      tier: db-custom-1-3840