name: bidrag-stonad
ingresses:
  - https://bidrag-stonad.intern.nav.no
dbname: bidrag-stønad-prod
kafka:
  pool: nav-prod
kafka-topic-vedtak: bidrag.vedtak
azureAccessInbound:
  - application: bidrag-stonad
    namespace: bidrag
    cluster: prod-gcp
spec:
  replicas:
    min: 2
    max: 4
  gcp:
    sqlInstances:
      tier: db-custom-1-3840
      diskAutoresize: true      