name: bidrag-stonad
ingresses:
  - https://bidrag-stonad.intern.nav.no
dbname: bidrag-stonad-prod
kafka:
  pool: nav-prod
kafka-topic-vedtak: bidrag.vedtak
spring-profiles: live,nais,database-legacy
azureAccessInbound:
  - application: bidrag-behandling
    namespace: bidrag
    cluster: prod-gcp
  - application: bisys
    namespace: bidrag
    cluster: prod-fss
spec:
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 50m
      memory: 512Mi
  gcp:
    sqlInstances:
      tier: db-custom-1-3840
      diskAutoresize: true      