-- Table: periode

-- DROP TABLE periode;

CREATE TABLE IF NOT EXISTS periode
(
    periode_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    periode_fom date NOT NULL,
    periode_til date,
    stonad_id integer NOT NULL,
    vedtak_id integer NOT NULL,
    periode_gjort_ugyldig_av_vedtak_id integer,
    belop float NOT NULL,
    valutakode varchar(10) NOT NULL,
    resultatkode varchar(255) NOT NULL,
    CONSTRAINT periode_pkey PRIMARY KEY (periode_id),
    CONSTRAINT fk_stonad_id FOREIGN KEY (stonad_id)
        REFERENCES stonad (stonad_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (stonad_id, periode_fom, periode_gjort_ugyldig_av_vedtak_id)
)

    TABLESPACE pg_default;