-- Table: stonad_mottaker_id_historikk

-- DROP TABLE stonad_mottaker_id_historikk;

CREATE TABLE IF NOT EXISTS mottaker_id_historikk
(
    stonad_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    mottaker_id_endret_fra varchar(20) NOT NULL,
    mottaker_id_endret_til varchar(20) NOT NULL,
    endret_av character(7) NOT NULL,
    endret_timestamp timestamp DEFAULT now() NOT NULL,
    CONSTRAINT mottaker_id_historikk_pkey PRIMARY KEY (stonad_id, endret_timestamp),
    CONSTRAINT fk_stonad_id FOREIGN KEY (stonad_id)
        REFERENCES stonad (stonad_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (stonad_id, endret_timestamp)
)

    TABLESPACE pg_default;