-- Table: stonad

-- DROP TABLE stonad;

CREATE TABLE IF NOT EXISTS stonad
(
    stonad_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    enhet_id character(4) NOT NULL,
    opprettet_av character(7) NOT NULL,
    opprettet_timestamp timestamp DEFAULT now() NOT NULL,
    CONSTRAINT stonad_pkey PRIMARY KEY (stonad_id)
)

    TABLESPACE pg_default;